/**
 * 招标采购常量统一导出
 * @module modules/bidding/constants
 */

// 映射常量
export {
  BID_SUBJECT_LABELS,
  QUALIFICATION_REQUIREMENT_LABELS,
  ACCEPT_JOINT_BID_LABELS,
  ACCEPT_AGENT_BID_LABELS,
  EVALUATION_METHOD_LABELS,
  EVALUATION_METHOD_DESCRIPTIONS,
  EVALUATION_SUMMARY_RANKING,
  DETAILED_EVALUATION,
  FINANCIAL_STATUS_REQUIREMENT_LABELS,
  RECENT_PROJECT_REQUIREMENT_LABELS,
  ALLOW_ALTERNATIVE_BID_LABELS,
  IS_SMALL_MEDIUM_ENTERPRISE_LABELS,
  BID_BOND_FORM_LABELS,
  PERFORMANCE_BOND_FORM_LABELS,
  BANK_GUARANTEE_REQUIREMENT_LABELS,
  PROOF_MATERIAL_LABELS,
  NO_NEGATIVE_DEVIATION_LABELS,
} from './mappings';
